services: 
  mongodb: 
    image: mongo:latest 
    restart: always 
    ports: 
      - "27017:27017" 
    environment: 
      MONGO_INITDB_DATABASE: sirkonia 
    volumes: 
      - mongodb_data:/data/db 
 
  redis: 
    image: redis:latest 
    ports: 
      - "6379:6379" 
    volumes: 
      - redis_data:/data 
 
volumes: 
  mongodb_data: 
  redis_data:
